# Generated by Django 2.2.7 on 2019-11-30 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('soft_cap', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('tokens_amount', models.PositiveIntegerField()),
                ('token_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundings', to='organisations.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='FundingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_amount', models.PositiveIntegerField()),
                ('token_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fundings.Funding')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
