# Generated by Django 2.2.7 on 2019-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingentry',
            options={'verbose_name_plural': 'Funding Entries'},
        ),
        migrations.AlterField(
            model_name='funding',
            name='soft_cap',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='token_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fundingentry',
            name='token_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
