# Generated by Django 2.2.7 on 2019-11-30 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0002_auto_20191130_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingentry',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Funding Entries'},
        ),
        migrations.AddField(
            model_name='fundingentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
