# Generated by Django 2.2.7 on 2019-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0003_auto_20191130_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
