# Generated by Django 2.2.7 on 2019-12-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0004_auto_20191130_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingentry',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
